### ISSUE TITLE
写的啥玩意

### ISSUE THREAD

**Issue by cc0411** [CloudWise-OpenSource/OMP#28]
你试试install能跑通吗 各种缺文件就能执行个本地ip

**Comment by soulferryman** [comment]
安装包已更新，您根据readme的部署流程再试试，这次应该没问题了

**Comment by Neeke** [comment]
CentOS安装包
wget -c https://github.com/CloudWise-OpenSource/OMP/releases/download/Release-v0.5.0/omp_open-0.5.tar.gz
