### ISSUE TITLE
是否支持在应用安装后创建数据库账号的使用场景？

### ISSUE THREAD

**Issue by bijianpeng** [CloudWise-OpenSource/OMP#44]
应用会使用自己的数据库账号，但是安装前数据中并没有创建这个账号，这就需要在通过omp安装应用后，能够触发执行一个创建数据库账号的操作
请问现在是否有这样的功能？

**Comment by zzjackaa** [comment]
并不可以，如果有必要可以尝试常规操作后，修改omp_server/omp_server/settings.py这个文件 这个是django项目配置文件 修改DATABASES这个值，改为自己的数据库账号密码库名等信息。然后使用 component/env/bin/python3.8 omp_server/manage.py migrate进行写库。然后重启omp即可

**Comment by bijianpeng** [comment]
我所说的并不是omp自己的数据库，而是通过omp安装的数据库。
通过omp安装应用时，应用依赖数据库服务，需要对数据库进行初始化，比如说建库，建账号等操作

**Comment by zzjackaa** [comment]
自定义安装数据库如（mysql）一般进行install.py和init.py（自行适配没有强制要求，omp只接受退出码）。 install.py一般做的是启停脚本，配置变更等操作，这个尽可能密等化操作（后续可能会更新类似配置更新等功能）。init.py一般进行数据库的初始化。例如添加权限等非幂等操作（上述的创建账号等操作放这）。  各自的安装参数都会下发到对应节点的安装目录下的omp_pakcages/xxxx.json中。尝试使用demo试一下。看一下json就能知晓
