### ISSUE TITLE
我看了一下demo，好像OMP不支持给业务代码升级

### ISSUE THREAD

**Issue by czxin788** [CloudWise-OpenSource/OMP#46]
我看了一下应用商店，看起来像是安装软件包的，是一次性工作。
有没有像jenkins那种，可以支持给业务代码发版升级的功能。

或者像spug这样的发布https://demo.spug.cc/
![image](https://user-images.githubusercontent.com/13861904/211740855-edba2c44-4989-4c07-8e6b-90cc7a6cb1b6.png)

**Comment by zzjackaa** [comment]
没有类似功能，他的前身是有jenkins打包的，包的制作（yaml，升级安装初始化升级回滚脚本）都是通过流水线完成，然后通过调用omp平台 后台的升级命令完成升级。升级流程是通过omp实现的。升级过程大致是，停止对应服务进程，升级包发送到对应节点，执行升级脚本（自制），omp服务配置（yaml内变量）变更，服务启动。
