### ISSUE TITLE
缺少配置文件

### ISSUE THREAD

**Issue by drummerglen** [CloudWise-OpenSource/OMP#5]
分支：dev
运行安装报错：
[root@OMP omp]# bash scripts/install.sh x.x.x.x
Traceback (most recent call last):
  File "/data/omp/scripts/source/update_conf.py", line 17, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
OMP配置更新失败
[root@OMP omp]#

**Comment by BugMing1024** [comment]
源码包下载地址已更新至README中，可通过最新安装包进行相关测试。
