### ISSUE TITLE
能否提供arm架构的监控Agent包？

### ISSUE THREAD

**Issue by w18211679321** [CloudWise-OpenSource/OMP#51]
试了下监控arm架构的服务器，有编译不兼容问题。
尝试重新编译了个python环境替换后，主机agent可正常处理。
但发现监控agent中的内容是已编译好的，所以能否提供监控agent的源码？或者提供支持arm架构的编译后文件？

**Comment by bijianpeng** [comment]
支持，同样需要arm架构下的监控包

**Comment by soulferryman** [comment]
在下一个版本中会考虑加入
