### ISSUE TITLE
界面上无法新增账号，应该如何添加账号？

### ISSUE THREAD

**Issue by jsp-kld** [CloudWise-OpenSource/OMP#54]

**Comment by czxin788** [comment]
我也有此困惑
也没有webshell
![image](https://user-images.githubusercontent.com/13861904/223028104-0463964f-29f8-4ac6-9a25-2f0242ed0874.png)

**Comment by soulferryman** [comment]
目前这个功能还没有开源，在后续的版本中会有规划

**Comment by Rosso-Wang** [comment]
可参考如下操作
![img_v2_7b899567-ceb7-4dca-8b8c-7be05550a78g](https://user-images.githubusercontent.com/59380115/223615762-65debd5c-ec0e-4665-911c-ce7b5e5608d6.jpg)
